{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"with_stress_pattern\",\"Parameter1\",\"Transform Sample File\",\"Sample File\",\"Transform File\",\"Parameter2\",\"Transform Sample File (2)\",\"Sample File (2)\",\"Transform File (2)\",\"Sample File (3)\",\"Parameter3\",\"Transform Sample File (3)\",\"Transform File (3)\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.126.1261.0 (24.02)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Transform Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Csv.Document(Parameter1,[Delimiter=\"\t\", Columns=11, Encoding=874, QuoteStyle=QuoteStyle.None]),\r",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])\r",
          "in\r",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "f74501f2-3a3a-43c1-8a11-1af851391716",
        "queryGroup": "Transform File from with_stress_pattern"
      },
      {
        "name": "Parameter1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "1810de00-1217-422f-9d31-032111e6de5b",
        "queryGroup": "Transform File from with_stress_pattern\\Helper Queries"
      },
      {
        "name": "Sample File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"D:\\DA\\Stress-Pattern-Occurrence-in-English-Words\\dataset\\with_stress_pattern\"),",
          "    #\"D:\\DA\\Stress-Pattern-Occurrence-in-English-Words\\Stress-Pattern-Occurrence-in-English-Words\\dataset\\with_stress_pattern\\_1_with_stress_patterns tsv\" = Source{[#\"Folder Path\"=\"D:\\DA\\Stress-Pattern-Occurrence-in-English-Words\\Stress-Pattern-Occurrence-in-English-Words\\dataset\\with_stress_pattern\\\",Name=\"1_with_stress_patterns.tsv\"]}[Content]",
          "in",
          "    #\"D:\\DA\\Stress-Pattern-Occurrence-in-English-Words\\Stress-Pattern-Occurrence-in-English-Words\\dataset\\with_stress_pattern\\_1_with_stress_patterns tsv\""
        ],
        "kind": "m",
        "lineageTag": "cf818778-633d-4dff-a387-390e19b3a319",
        "queryGroup": "Transform File from with_stress_pattern\\Helper Queries"
      },
      {
        "name": "Transform File",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter1 as binary) => let",
          "        Source = Csv.Document(Parameter1,[Delimiter=\"\t\", Columns=11, Encoding=874, QuoteStyle=QuoteStyle.None]),",
          "        #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "    in",
          "        #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "c2c18236-df14-459e-ae9c-7b6b0642468d",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File\"\"}\" ]",
        "queryGroup": "Transform File from with_stress_pattern\\Helper Queries"
      },
      {
        "name": "Parameter2",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (2)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (2)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "addbfef3-3e78-4e41-b228-80cc24b9896b",
        "queryGroup": "Transform File from with_stress_pattern (2)\\Helper Queries"
      },
      {
        "name": "Transform Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let\r",
          "    Source = Csv.Document(Parameter2,[Delimiter=\"\t\", Columns=13, Encoding=874, QuoteStyle=QuoteStyle.None]),\r",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])\r",
          "in\r",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "6066000f-6952-4d2c-926f-7798b38e1211",
        "queryGroup": "Transform File from with_stress_pattern (2)"
      },
      {
        "name": "Sample File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"D:\\DA\\Stress-Pattern-Occurrence-in-English-Words\\dataset\\with_stress_pattern\"),",
          "    #\"D:\\DA\\Stress-Pattern-Occurrence-in-English-Words\\Stress-Pattern-Occurrence-in-English-Words\\dataset\\with_stress_pattern\\_12_with_stress_patterns tsv\" = Source{[#\"Folder Path\"=\"D:\\DA\\Stress-Pattern-Occurrence-in-English-Words\\Stress-Pattern-Occurrence-in-English-Words\\dataset\\with_stress_pattern\\\",Name=\"12_with_stress_patterns.tsv\"]}[Content]",
          "in",
          "    #\"D:\\DA\\Stress-Pattern-Occurrence-in-English-Words\\Stress-Pattern-Occurrence-in-English-Words\\dataset\\with_stress_pattern\\_12_with_stress_patterns tsv\""
        ],
        "kind": "m",
        "lineageTag": "1e0dbd6c-2050-4dcb-a697-2b3fd1a05c1d",
        "queryGroup": "Transform File from with_stress_pattern (2)\\Helper Queries"
      },
      {
        "name": "Transform File (2)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter2 as binary) => let",
          "        Source = Csv.Document(Parameter2,[Delimiter=\"\t\", Columns=13, Encoding=874, QuoteStyle=QuoteStyle.None]),",
          "        #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "    in",
          "        #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "092c72de-be04-4bb4-a92d-dd0d7fe9fa74",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File (2)\"\"}\" ]",
        "queryGroup": "Transform File from with_stress_pattern (2)\\Helper Queries"
      },
      {
        "name": "Sample File (3)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Source = Folder.Files(\"D:\\DA\\Stress-Pattern-Occurrence-in-English-Words\\dataset\\with_stress_pattern\"),",
          "    Navigation1 = Source{0}[Content]",
          "in",
          "    Navigation1"
        ],
        "kind": "m",
        "lineageTag": "3117f603-f6ca-48c4-b3ef-2eb8df54ff37",
        "queryGroup": "Transform File from with_stress_pattern (3)\\Helper Queries"
      },
      {
        "name": "Parameter3",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Sample File (3)\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Sample File (3)\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "81a52567-2099-4808-8763-09e2f08d0ce0",
        "queryGroup": "Transform File from with_stress_pattern (3)\\Helper Queries"
      },
      {
        "name": "Transform Sample File (3)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Source = Csv.Document(Parameter3,[Delimiter=\"\t\", Columns=13, Encoding=874, QuoteStyle=QuoteStyle.None]),",
          "    #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "in",
          "    #\"Promoted Headers\""
        ],
        "kind": "m",
        "lineageTag": "f95a9ef4-a2be-4505-909b-b8449921abc0",
        "queryGroup": "Transform File from with_stress_pattern (3)"
      },
      {
        "name": "Transform File (3)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Source = (Parameter3) => let",
          "        Source = Csv.Document(Parameter3,[Delimiter=\"\t\", Columns=13, Encoding=874, QuoteStyle=QuoteStyle.None]),",
          "        #\"Promoted Headers\" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])",
          "    in",
          "        #\"Promoted Headers\"",
          "in",
          "    Source"
        ],
        "kind": "m",
        "lineageTag": "a879a5b5-e7b9-4a63-84df-2f5daa9bf989",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transform Sample File (3)\"\"}\" ]",
        "queryGroup": "Transform File from with_stress_pattern (3)\\Helper Queries"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from with_stress_pattern"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from with_stress_pattern\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ],
        "folder": "Transform File from with_stress_pattern (2)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from with_stress_pattern (2)\\Helper Queries"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "4"
          }
        ],
        "folder": "Transform File from with_stress_pattern (3)"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transform File from with_stress_pattern (3)\\Helper Queries"
      }
    ],
    "sourceQueryCulture": "th-TH",
    "tables": [
      {
        "name": "with_stress_pattern",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "Source.Name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a02eb6b8-7338-4f18-bf01-acc7615e317b",
            "sourceColumn": "Source.Name",
            "summarizeBy": "none"
          },
          {
            "name": "Word",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21c45520-11bb-4a1f-a294-d03309fe9721",
            "sourceColumn": "Word",
            "summarizeBy": "none"
          },
          {
            "name": "FREQcount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fe4b8e74-3d6f-4e5e-8fbe-be397b991915",
            "sourceColumn": "FREQcount",
            "summarizeBy": "sum"
          },
          {
            "name": "CDcount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b52e9a55-87b7-445d-92de-f0e9b9ec177a",
            "sourceColumn": "CDcount",
            "summarizeBy": "sum"
          },
          {
            "name": "FREQlow",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e8bc6bf-cdb9-48a2-ba09-7b2dfa0d2d8a",
            "sourceColumn": "FREQlow",
            "summarizeBy": "sum"
          },
          {
            "name": "Cdlow",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8ae54f45-bf60-47f7-ae95-920448ad6d11",
            "sourceColumn": "Cdlow",
            "summarizeBy": "sum"
          },
          {
            "name": "SUBTLWF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d6dc8e19-d0f6-4bcf-badb-0077e5fefb6d",
            "sourceColumn": "SUBTLWF",
            "summarizeBy": "sum"
          },
          {
            "name": "Lg10WF",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0ad4cfd0-3c92-4d58-8169-12292254022f",
            "sourceColumn": "Lg10WF",
            "summarizeBy": "sum"
          },
          {
            "name": "SUBTLCD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "71f507b3-5040-4e3d-a5fa-80a626009bc4",
            "sourceColumn": "SUBTLCD",
            "summarizeBy": "sum"
          },
          {
            "name": "Lg10CD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b8145d29-0517-478e-8118-007a467f62d1",
            "sourceColumn": "Lg10CD",
            "summarizeBy": "sum"
          },
          {
            "name": "syllable_count",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2e6b2f4b-4013-4083-92a3-3ff733b7297e",
            "sourceColumn": "syllable_count",
            "summarizeBy": "sum"
          },
          {
            "name": "stress_pattern",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "369dcf27-c461-4782-9232-ca3c30994c68",
            "sourceColumn": "stress_pattern",
            "summarizeBy": "sum"
          },
          {
            "name": "primary_stress_position",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d0b2ef8b-7c4c-4ac8-bff8-913778611224",
            "sourceColumn": "primary_stress_position",
            "summarizeBy": "sum"
          },
          {
            "name": "secondary_stress_position",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b6db818d-59e3-494c-9bd9-b55fe33c9329",
            "sourceColumn": "secondary_stress_position",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "d824df33-cee3-4aa2-b8f5-79dfddedd8f0",
        "partitions": [
          {
            "name": "with_stress_pattern",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Folder.Files(\"D:\\DA\\Stress-Pattern-Occurrence-in-English-Words\\dataset\\with_stress_pattern\"),",
                "    #\"Filtered Hidden Files1\" = Table.SelectRows(Source, each [Attributes]?[Hidden]? <> true),",
                "    #\"Invoke Custom Function1\" = Table.AddColumn(#\"Filtered Hidden Files1\", \"Transform File (3)\", each #\"Transform File (3)\"([Content])),",
                "    #\"Renamed Columns1\" = Table.RenameColumns(#\"Invoke Custom Function1\", {\"Name\", \"Source.Name\"}),",
                "    #\"Removed Other Columns1\" = Table.SelectColumns(#\"Renamed Columns1\", {\"Source.Name\", \"Transform File (3)\"}),",
                "    #\"Expanded Table Column1\" = Table.ExpandTableColumn(#\"Removed Other Columns1\", \"Transform File (3)\", Table.ColumnNames(#\"Transform File (3)\"(#\"Sample File (3)\"))),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Expanded Table Column1\",{{\"Source.Name\", type text}, {\"Word\", type text}, {\"FREQcount\", Int64.Type}, {\"CDcount\", Int64.Type}, {\"FREQlow\", Int64.Type}, {\"Cdlow\", Int64.Type}, {\"SUBTLWF\", type number}, {\"Lg10WF\", type number}, {\"SUBTLCD\", type number}, {\"Lg10CD\", type number}, {\"syllable_count\", Int64.Type}, {\"stress_pattern\", Int64.Type}, {\"primary_stress_position\", Int64.Type}, {\"secondary_stress_position\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_e5e191cc-3fb8-4cea-8535-0527a8c9d313",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8a36aa62-97ed-4491-a03d-be14252b0ba7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3d2dc80b-478d-4e71-b7db-3d7564de5926",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "3e66f5f2-889c-4d83-8d28-1af833fc036a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "00fe0296-4976-4608-90c8-92a8893331f4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5bf525c9-eff0-420b-95de-8cf0aee20331",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "504acfd0-2ec9-4624-9d8a-1b30ef16af17",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "47a0e339-5308-4620-8c34-a9ee908cc617",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "287f0e51-82fa-4209-9fe8-1ef7acd79fd4",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "44fb16c6-9174-4593-81dc-08d08a660b42",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "eb51f230-ddbc-4820-9c0a-95d3c1e0b90a",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "2d72406e-ed0b-4e29-ad5b-225e44387e56",
                "ordinal": 3
              }
            ],
            "lineageTag": "69d1928d-6eb3-4267-ad05-796b03afea7f"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "8b359981-8a81-433b-93ea-2a046e6c3b14",
        "partitions": [
          {
            "name": "DateTableTemplate_e5e191cc-3fb8-4cea-8535-0527a8c9d313",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}